apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:DlxaH6MG7z6QEKpPM/dzxacQYsyv83M0CAGvqqEORYsVM9bT0XPlNxrV6MqLuTok7OAf/dPhEJhoVPGdeLaI43v300mp47/6RkpyfGe7tTL9K7v7bQ7GRbWNzOk8cDDTYXkDeNZ5STVlAtJ1E7vAAikVaeCnUjRNDkNxi4LzL5BLr5qegFK5KuAHXcMQhQrSWy46JmDso8fce/b4i+r5Q7ogVrOBOleLvKwL/H8P8jUrc+aRXCLpQKGjv/8CdmtvCBQmU61MGsCGJL2yewWBKT5vVB9NMdasMaegc2oXc3zS7Rohvea4fud0Jsw=,iv:jjMp1DFZBP0sD3TpN+bXZYP3/SMdE9x5XRnK7knuCO0=,tag:bIqcW68SKKcj46pgcvyoKg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMjRKMy9XeC9qQXZHcjFw
            VFZOVTA5RjVUTkpsUHBiUnNRT2EvaVBYRTJnCnc1RGpwSEJ5cGppWEdOd0FEamFq
            STJRckdaeWdKQVVOMkhYUW5FREdtYlkKLS0tIDFseXBKTFF6Vk1qRU5aVlRlVTM0
            OEx6dHBvSk9WUTBxeVFZSGYvVHlWYncKhLkx5YNwxt8xhBLnFTZnYlubUH0MeYVg
            J/u8XTpiu6T6jDxyN7wRGIYZloJ4iDGxmKMv8X6fKJHbAqDfmCiMUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jdj7hg3fa3ddqyg3jjqttxzfxqqjnvghtcm3rgdtkvht4g5xguyqumm2rp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:27:15Z"
    mac: ENC[AES256_GCM,data:wmtJ0rSKrDOk7Ly/NF4XPY5IgFlRnQ1djXQ6skGOPsTsSCv68Fb/2iu6KuT5G8rB91nQs4zXAd904HLtw72Bhdr+6M/VfeTIWQQhhiZAAWwSO4sl2Yahg7OeJd32VODT6/gPd/zHlwKpw/XSRL45egDWH/2NVmQ1St9MUCoY3wA=,iv:qp/LtyDpERedJRtU838n9KghnSV4yKx1B927zaXvNhk=,tag:LzibIIk6aygVoQZ230N5XA==,type:str]
    version: 3.13.1
